addons:
    apt:
        packages:
            - cmake
        sources:
            - kalakris-cmake

language: c++

before_script:
    - mkdir build
    - cd build
    - cmake ..

compiler:
    - clang
    - gcc
