addons:
    apt:
        packages:
            - cmake
            - cmake-data
            - clang
        sources:
            - george-edison55-precise-backports
            - ubuntu-toolchain-r-test

language: c++

before_script:
    - mkdir build
    - cd build
    - cmake ..

script:
    - make

compiler:
    - clang
    - gcc
